version: '2'
services:
    digitalblog-app:
        image: digitalblog
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://digitalblog-mysql:3306/digitalblog?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    digitalblog-mysql:
        extends:
            file: mysql.yml
            service: digitalblog-mysql
